### ISSUE TITLE
Archivos Base datos

### ISSUE THREAD

**Issue by Gonen09** [reisig/proyecto_aplicaciones#21]
Como realice cambios en la datos y a pedido de @Caraya0100 , necesito saber en que archivos utilizaron la base de datos para poder actualizarlos con la nueva base de datos, saludos

**Comment by ariel26** [comment]
@Gonen09 necesito que le agregues un contador que se incremente automaticamente al ingresar un elemento a la tabla repositorio, esto debido a que en el ejemplo del visor de imagenes que vamos a utilizar usare las mismas imagenes muchas veces, entonces si quiero insertar la misma imagen a la tabla tengo que necesariamente copiar la imagen y cambiarle el nombre (debido a que la ruta de la imagen es la clave primaria), asi que eso seria, agregar un contandor y poner ese contador como PK

**Comment by Caraya0100** [comment]
No quiero ser entremetido xD pero esa es pega tuya @ariel26 lo que debes hacer es modificar la tabla y agregarle una columna id que sea auto_increment (creo que esa era) ya que se necesita un dato único para cuando se borre una imagen, la ruta no puede ser la clave primaria.

**Comment by Gonen09** [comment]
Con la "reunion" de hoy @ariel26 queda a cargo de administrar la base de datos designado por @Caraya0100, aqui los cambios que realice para que ariel cree la version final.

Cambios en la BD v7:

Los cambios de nombres a las columnas son sugerencias.

Tabla repositorio: cambio de nombres en columnas 

  descripcion_breve -> descripcion
  tipo_teñido -> tincion
  
Tabla usuario: Eliminado id_asignatura, cambio de nombre a columna 

  tipo_usuario -> tipo

Tabla asignatura: cambio de nombre a columna 

	nombre_asignatura -> nombre
	profesor_acargo -> rut_profesor  (no solo de nombre, es mejor administrarlo asi)

Tabla guias: cambio de nombre a columna 

	IDasignatura -> id_asignatura

Tabla contenido: cambio de nombre a columna 

	tipo -> tipo_respuesta

Tabla seleccion_multiple : cambio de nombre a columna

	Letra -> Tipo
 	Alternativa -> Valor_alternativa (en vez de guardar alternativa A guardo su valor de respuesta, A) periferica, guardo periferica)


Tabla preguntas: igual
Tabla respuestas: igual

- Se creó la tabla usuarios_asignatura con los campos "rut_usuario" y "id_asignatura".

- Constantes de tablas:

usuarios.tipo:
- ADMINISTRADOR,
- PROFESOR,
- ALUMNO.

guias.estado:
- ACTIVA,
- INACTIVA

preguntas.tipo_respuesta:
- TITULO,
- TEXTO,
- AREA,
- MULTIPLE.

seleccion_multiple.tipo:
- CHECKBOX,
- RADIO,
- LISTA.
