### ISSUE TITLE
Recorrer nodos HTML

### ISSUE THREAD

**Issue by Gonen09** [reisig/proyecto_aplicaciones#22]
Necesito saber si alguien sabe alguna forma de obtener todos los nodos hijos que estan dentro de una etiqueta con un id especifico, ejemplo:
div id = "opciones" 
   h1 Titulo h1
   p hola p
div

Necesito recuperar el h1 y el p hijos del div, para no hacer tantos id's.

**Comment by Caraya0100** [comment]
Hoy tampoco podre ver tu código, pero para hacer eso puedes hacerlo de dos formas:

1. Usando jquery: 
 ```
$('#opciones h1').html();
$('#opciones p').html();
```

2. o con PHP: Agregando un atributo name al h1 y al p, para después recuperarlos con $_POST o $_GET, si es que están dentro de un form.

¿Para que querías recuperar esos datos?

Si es para guardarlos en la base de datos, es mucho mas cómodo hacerlo con post o get.
