### ISSUE TITLE
Detalle en la bd

### ISSUE THREAD

**Issue by Gonen09** [reisig/proyecto_aplicaciones#32]
@ariel26 man como borraron la tabla asigantura, ahora no tengo como saber quien creo la guia, lo que necesito es agregar la columna rut_creador o algo asi para saber quien la creo, saludos

**Comment by ariel26** [comment]
@Gonen09 , me informaron por interno que el grupo de @reisig, @rayala83 e @ivonnerojo van a necesitar el uso de la tabla asignatura, por lo cual la base de datos quedara como estaba planteada anteriormente, asi que si te funcionaba bien de esa manera el problema estaria solucionado
